# Generated by Django 4.0.4 on 2022-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_alter_county_options_county_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
