# Generated by Django 4.0.5 on 2022-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_hospital_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images'),
        ),
    ]
