# Generated by Django 4.0.4 on 2022-05-25 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_parent_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_no', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('mothers_name', models.CharField(blank=True, max_length=254, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=254, null=True)),
                ('date_of_registration', models.DateTimeField()),
                ('date_of_birth', models.DateTimeField()),
                ('birth_county', models.CharField(choices=[(1, 'NAIROBI COUNTY'), (2, 'KISUMU COUNTY'), (3, 'NYANDARUA COUNTY'), (4, 'NAKURU COUNTY'), (5, 'KERICHO COUNTY'), (6, 'MAKUENI COUNTY'), (7, 'LAIKIPIA COUNTY'), (8, 'BUSIA COUNTY'), (9, 'TANA RIVER COUNTY'), (10, 'WEST POKOT COUNTY'), (11, 'BARINGO COUNTY'), (12, 'BOMET COUNTY'), (13, 'BUNGOMA COUNTY'), (14, 'BUSIA COUNTY'), (15, 'ELGEYO MARAKWET COUNTY'), (16, 'EMBU COUNTY'), (17, 'GARISSA COUNTY'), (18, 'HOMA BAY COUNTY'), (19, 'ISIOLO COUNTY'), (20, 'KAKAMEGA COUNTY'), (21, 'KERICHO COUNTY'), (22, 'KIAMBU COUNTY'), (23, 'KILIFI COUNTY'), (24, 'LAMU COUNTY'), (25, 'MACHINGA COUNTY'), (26, 'MANDERA COUNTY'), (27, 'MARSABIT COUNTY'), (28, 'MOMBASA COUNTY'), (29, 'MULANGO COUNTY'), (30, 'NAKURU COUNTY'), (31, 'NANDI COUNTY'), (32, 'NAROK COUNTY'), (33, 'NYANDARUA COUNTY'), (34, 'NYERI COUNTY'), (35, 'SAMBURU COUNTY'), (36, 'SIAYA COUNTY'), (37, 'TAITA TAVETA COUNTY'), (38, 'TANA RIVER COUNTY'), (39, 'THARAKA COUNTY'), (40, 'VIHIGA COUNTY'), (41, 'WAJIR COUNTY'), (42, 'WEST POKOT COUNTY'), (43, 'GOMBE COUNTY'), (44, 'BARINGO COUNTY'), (45, 'BOMET COUNTY'), (46, 'BUNGOMA COUNTY'), (47, 'BUSIA COUNTY')], max_length=254)),
                ('resident_county', models.CharField(blank=True, choices=[(1, 'NAIROBI COUNTY'), (2, 'KISUMU COUNTY'), (3, 'NYANDARUA COUNTY'), (4, 'NAKURU COUNTY'), (5, 'KERICHO COUNTY'), (6, 'MAKUENI COUNTY'), (7, 'LAIKIPIA COUNTY'), (8, 'BUSIA COUNTY'), (9, 'TANA RIVER COUNTY'), (10, 'WEST POKOT COUNTY'), (11, 'BARINGO COUNTY'), (12, 'BOMET COUNTY'), (13, 'BUNGOMA COUNTY'), (14, 'BUSIA COUNTY'), (15, 'ELGEYO MARAKWET COUNTY'), (16, 'EMBU COUNTY'), (17, 'GARISSA COUNTY'), (18, 'HOMA BAY COUNTY'), (19, 'ISIOLO COUNTY'), (20, 'KAKAMEGA COUNTY'), (21, 'KERICHO COUNTY'), (22, 'KIAMBU COUNTY'), (23, 'KILIFI COUNTY'), (24, 'LAMU COUNTY'), (25, 'MACHINGA COUNTY'), (26, 'MANDERA COUNTY'), (27, 'MARSABIT COUNTY'), (28, 'MOMBASA COUNTY'), (29, 'MULANGO COUNTY'), (30, 'NAKURU COUNTY'), (31, 'NANDI COUNTY'), (32, 'NAROK COUNTY'), (33, 'NYANDARUA COUNTY'), (34, 'NYERI COUNTY'), (35, 'SAMBURU COUNTY'), (36, 'SIAYA COUNTY'), (37, 'TAITA TAVETA COUNTY'), (38, 'TANA RIVER COUNTY'), (39, 'THARAKA COUNTY'), (40, 'VIHIGA COUNTY'), (41, 'WAJIR COUNTY'), (42, 'WEST POKOT COUNTY'), (43, 'GOMBE COUNTY'), (44, 'BARINGO COUNTY'), (45, 'BOMET COUNTY'), (46, 'BUNGOMA COUNTY'), (47, 'BUSIA COUNTY')], max_length=50, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parent')),
            ],
            options={
                'verbose_name_plural': 'Children',
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('time_given', models.CharField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'db_table': 'vaccines',
            },
        ),
        migrations.CreateModel(
            name='ChildImmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('height', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('comment', models.TextField(blank=True, max_length=254, null=True)),
                ('date_given', models.DateTimeField()),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccines')),
            ],
            options={
                'verbose_name': 'Child Immunization',
                'verbose_name_plural': 'Child Immunizations',
                'db_table': 'child_immunization',
            },
        ),
    ]
