# Generated by Django 4.0 on 2022-05-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_child_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
