# Generated by Django 4.0.4 on 2022-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_child_profile_picture_alter_child_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childimmunization',
            name='date_given',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
