# Generated by Django 4.0.4 on 2022-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_childimmunization_date_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
