# Generated by Django 4.0 on 2022-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_child_birth_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='vaccine_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
