# Generated by Django 4.0 on 2022-06-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vaccines_vaccine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccines',
            old_name='vaccine_id',
            new_name='vac_id',
        ),
    ]
