# Generated by Django 4.0 on 2022-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_vaccine_id_vaccines_vac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='childimmunization',
            name='child_immunization_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
