# Generated by Django 4.0 on 2022-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_childimmunization_child_immunization_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccines',
            old_name='vac_id',
            new_name='vaccine_id',
        ),
        migrations.AddField(
            model_name='child',
            name='child_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
