# Generated by Django 4.0 on 2022-06-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vaccines_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='time_given',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
