# Generated by Django 4.0 on 2022-06-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_vaccines_time_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='time_given',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
