# Generated by Django 4.0 on 2022-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_vaccines_time_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='duration_given',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='time_given',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
