# Generated by Django 4.0.4 on 2022-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_childimmunization_immunization_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='days_to_vaccine',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
