# Generated by Django 4.0.5 on 2022-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_child_height_alter_child_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
