# Generated by Django 4.0 on 2022-05-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctor_user_alter_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='images/parents_profile/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='images/doctors_profile/%Y/%m'),
        ),
    ]
