# Generated by Django 4.0.4 on 2022-05-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_parent_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_id',
        ),
    ]
