# Generated by Django 4.0 on 2022-06-02 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_hospital_alter_moh_options_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='salutation',
            field=models.CharField(choices=[('Dr', 'Dr'), ('RN', 'RN')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
