# Generated by Django 4.0 on 2022-06-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_doctor_date_joined_doctor_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
