# Generated by Django 4.0.5 on 2022-06-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_parent_parent_id_alter_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctors',
        ),
        migrations.AlterModelTable(
            name='moh',
            table='moh',
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
