# Generated by Django 4.0.5 on 2022-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_doctor_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='images/doctors_profile/%Y/%m'),
        ),
    ]
